# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-21 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('AId', models.AutoField(primary_key=True, serialize=False)),
                ('AType', models.IntegerField()),
                ('AAdmin', models.ImageField(upload_to='')),
                ('ARegister', models.CommaSeparatedIntegerField(max_length=30)),
                ('AUnregister', models.CommaSeparatedIntegerField(max_length=30)),
                ('AMaxRegister', models.ImageField(upload_to='')),
                ('ACreateTime', models.DateField()),
                ('AEntryDDL', models.DateField()),
                ('AStartTime', models.DateField()),
                ('AEndTime', models.DateField()),
                ('AStatus', models.IntegerField()),
                ('ATitle', models.CharField(max_length=30)),
                ('ALocation', models.CharField(max_length=40)),
                ('AInfo', models.CharField(max_length=50)),
                ('ASummary', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('Mid', models.AutoField(primary_key=True, serialize=False)),
                ('MisRead', models.BooleanField()),
                ('MContent', models.CharField(max_length=50)),
                ('MFrom', models.IntegerField()),
                ('MTo', models.ImageField(upload_to='')),
                ('MTime', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('UId', models.AutoField(primary_key=True, serialize=False)),
                ('UInAct', models.CommaSeparatedIntegerField(max_length=20)),
                ('UInActNum', models.IntegerField()),
                ('UOrganizedAct', models.CommaSeparatedIntegerField(max_length=20)),
                ('UOrganizedNum', models.IntegerField()),
                ('UTags', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='UserBase',
            fields=[
                ('UId', models.AutoField(primary_key=True, serialize=False)),
                ('UPrivateEmail', models.EmailField(max_length=254)),
                ('UPublicEmail', models.EmailField(max_length=254)),
                ('UName', models.CharField(max_length=30)),
                ('UAvatar', models.ImageField(upload_to='')),
                ('UPassword', models.CharField(max_length=30)),
                ('UInfo', models.CharField(max_length=50)),
                ('UStatus', models.IntegerField()),
                ('UFollow', models.CommaSeparatedIntegerField(max_length=10)),
                ('UFollowed', models.CommaSeparatedIntegerField(max_length=10)),
                ('UMessage', models.CommaSeparatedIntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserTimeline',
            fields=[
                ('UId', models.AutoField(primary_key=True, serialize=False)),
                ('UTimelineFrom', models.CommaSeparatedIntegerField(max_length=10)),
                ('UTimelineAct', models.CommaSeparatedIntegerField(max_length=10)),
                ('UTimelineContent', models.CharField(max_length=1000)),
            ],
        ),
    ]
